# -*- coding: utf-8 -*-
"""QRCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1QCMG-VA2KDWq_61KJAc28-afNajFnG
"""

!pip install qrcode

import qrcode

url = input("Enter the URL: ")

img = qrcode.make(url)

img.save('qrcode.png')
print('qrcode created successfully')